name: Android CI
on:
  pull_request:
    branches:
      - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew test